server:
  port: 8000

spring:
  application:
    name: moa-meetingplatform
  profiles:
    default: prod
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
  jwt:
    secret: asdsadasdamklmdklamdklamsldamsdlkasmdkamdklamsdlkm1m13m1kl32m1sadmlsadmkaldmaskldmkla
    expiration: 86400000
    header: Authorization
    prefix: Bearer
    refresh:
      expiration: 86400000
      header: Refresh
      prefix: Bearer

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**
