server:
  port: 8000

spring:
  application:
    name: SSGPOINT_APP
  profiles:
    default: temp
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**
