spring:
  config:
    activate:
      on-profile: prod

  jpa:
    properties:
      hibernate:
        ddl_auto: update
        format_sql: true
        show_sql: true

  data:
    redis:
      port: 6379
      host: 10.176.8.126
      connect-timeout: 1000

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://10.240.80.11:3306/moa_user
        read-only: false
        username: root
        password: ${MASTER_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://10.240.80.13:3306/moa_user
        read-only: true
        username: root
        password: ${SLAVE_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

  # Kafka 설정 추가
  kafka:
    bootstrap-servers: 10.176.12.164:9092 # Kafka 서비스의 CLUSTER-IP와 포트 -> 나중에 적용
    #    bootstrap-servers: 34.64.189.14:9092 # Kafka 서비스의 EXTERNAL-IP와 포트
    consumer:
      group-id: my-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    com.moa.user: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


JWT:
  secret-key: ${JWT_SECRET}
  expiration-time: 86400000 # 1 day, 1000 * 60 * 60 * 24, 추후 수정
  header: Authorization
  prefix: Bearer

