spring:
  config:
    activate:
      on-profile: local

  jpa:
    properties:
      hibernate:
        ddl_auto: update
        format_sql: true
        show_sql: true

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/moa_user
        read-only: false
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/moa_user
        read-only: true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

logging.level:
  org.hibernate.orm.jdbc.bind: trace
  com.moa.user: DEBUG
