spring:
  config:
    activate:
      on-profile: prod

  jpa:
    properties:
      hibernate:
        ddl_auto: update  # 운영서버에서 원래는 validate 또는 none 으로 설정해야함
        format_sql: true
        show_sql: true

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://10.240.80.11:3306/moa_user
        read-only: false
        username: root
        password: ${MASTER_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://10.240.80.13:3306/moa_user
        read-only: true
        username: root
        password: ${SLAVE_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

logging.level: # 서버 디버깅용 임시 설정
  org.hibernate.orm.jdbc.bind: trace
  com.moa.user: DEBUG

JWT:
  secret-key: ${JWT_SECRET}
  expiration-time: 86400000 # 1 day, 1000 * 60 * 60 * 24, 추후 수정
  header: Authorization
  prefix: Bearer