spring:
  config:
    activate:
      on-profile: prod

  jpa:
    properties:
      hibernate:
        ddl_auto: update  # 운영서버에서 원래는 validate 또는 none 으로 설정해야함
        format_sql: true
        show_sql: true

  datasource:
    master:
      hikari:
        jdbc-url: ${MASTER_DB_URL}
        read-only: false
        username: ${MASTER_DB_USERNAME}
        password: ${MASTER_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: ${SLAVE_DB_URL}
        read-only: true
        username: ${SLAVE_DB_USERNAME}
        password: ${SLAVE_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

logging.level: # 서버 디버깅용 임시 설정
  org.hibernate.orm.jdbc.bind: trace
  com.moa.user: DEBUG
