spring:
  config:
    activate:
      on-profile: temp

  jpa:
    properties:
      hibernate:
        ddl_auto: update
        format_sql: true
        show_sql: true

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://10.240.80.7:3306/moa_user
        read-only: false
        username: root
        password: ${MASTER_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://10.240.80.9:3306/moa_user
        read-only: true
        username: root
        password: ${SLAVE_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

logging.level:
  org.hibernate.orm.jdbc.bind: trace
  com.moa.user: DEBUG
