server:
  port: 8000

spring:
  application:
    name: user-service
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      port: 6379
      host: ${REDIS_URL}
      password: ${REDIS_PW}
      connect-timeout: 1000

  mail:
    host: smtp.gmail.com
    port: 587 # TLS
    username: ${MAIL_USER_NAME} #앱 비밀번호 발급받은 google 계정
    password: ${MAIL_PW} #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**


