spring:
  config:
    activate:
      on-profile: local

  jpa:
    properties:
      hibernate:
        ddl_auto: create
        format_sql: true
        show_sql: true

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/moa_user
        read-only: false
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/moa_user
        read-only: true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

logging.level:
  org.hibernate.orm.jdbc.bind: trace
  com.moa.user: DEBUG

jwt:
  secret-key: moamoadamoamoooooooamoooooooaaaaaaaaasecretsecretmo0o0o0o0o000o00oa
  expiration-time: 86400000
  header: Authorization
  prefix: Bearer